export enum AppIdPermission {
  VIEW_TEAMS = 1,
  EDIT_TEAMS = 2,
  DELETE_TEAMS = 3,
  CREATE_TEAMS = 4,
  VIEW_USERS = 5,
  CREATE_USERS = 6,
  EDIT_USERS = 7,
  ASSIGNMENT_DAYS_ON_SITE = 8,
  VIEW_DAYS_ON_SITE = 9,
  UPDATE_DAYS_ON_SITE = 10,
  CREATE_DAYS_ON_SITE = 11,
  DELETE_DAYS_ON_SITE = 12,
  VIEW_REQUEST = 13,
  VIEW_GENERALS_DAYS_ON_SITE = 18,
  VIEW_USERS_DAYS_ON_SITE = 19,
  CONFIG_USERS = 22,
  VIEW_NON_WORKINGS_DAYS = 23,
  CREATE_NON_WORKINGS_DAYS = 24,
  DELETE_NON_WORKINGS_DAYS = 25,
  VIEW_MANDATORY_DAYS = 26,
  CREATE_MANDATORY_DAYS = 27,
  DELETE_MANDATORY_DAYS = 28,
  VIEW_PARAMETERS = 32,
  UPDATE_PARAMETERS = 33,
  CREATE_BRANCHS = 34,
  VIEW_BRANCHS = 35,
  EDIT_BRANCHS = 36,
  DELETE_BRANCHS = 37,
  CREATE_SHIFTS = 38,
  VIEW_SHIFTS = 39,
  EDIT_SHIFTS = 40,
  DELETE_SHIFTS = 41,
  VIEW_WORK_SHIFTS = 42,
  CREATE_WORK_SHIFTS = 43,
  UPDATE_WORK_SHIFTS = 44,
  ASSIGNMENT_WORK_SHIFTS = 45,
  DELETE_WORK_SHIFTS = 46,
  VIEW_CONFIGURATION_DAYS = 47,
  CREATE_CONFIGURATION_DAYS = 48,
  VIEW_LEGAL_HOURS = 49,
  CREATE_LEGAL_HOURS = 50,
  UPDATE_LEGAL_HOURS = 51,
  VIEW_NOVELTYS = 52,
  CREATE_NOVELTYS = 53,
  VIEW_TYPE_NOVELTY = 54,
  VIEW_EVENT = 55,
  CREATE_EVENT = 56,
  VIEW_TYPE_EVENT = 57,
  UPDATE_NOVELTYS = 58,
  DELETE_NOVELTYS = 59,
  VIEW_WORK_SHIFT_NOVELTYS = 60,
  UPDATE_EVENT = 61,
  VIEW_NON_WORKINGS_DAYS_WORK_SHIFTS = 62,
  VIEW_POSITIONS = 63,
  CREATE_POSITIONS = 64,
  VIEW_TYPE_SHIFT = 65,
  VIEW_CUSTOM_REPORT = 69,
  VIEW_DASHBOARD = 70,
  VIEW_NON_WORKINGS_DAYS_WORKSHIFTS = 71,
  VIEW_TOLERANCE_MARKING_SHIFT = 72,
  VIEW_PAYROLL_SETTLEMENT_REPORT = 73,
  VIEW_ALTERNATION_REQUESTS = 74,
  VIEW_DEMAND_LEVEL = 78,
}

export const AppPermissions = {
  teams: {
    view: AppIdPermission.VIEW_TEAMS,
    edit: AppIdPermission.EDIT_TEAMS,
    delete: AppIdPermission.DELETE_TEAMS,
    create: AppIdPermission.CREATE_TEAMS,
  },
  users: {
    view: AppIdPermission.VIEW_USERS,
    create: AppIdPermission.CREATE_USERS,
    inactivate: AppIdPermission.EDIT_USERS,
    activate: AppIdPermission.EDIT_USERS,
    config: AppIdPermission.CONFIG_USERS,
  },
  daysOnSite: {
    view: AppIdPermission.VIEW_DAYS_ON_SITE,
    create: AppIdPermission.CREATE_DAYS_ON_SITE,
    update: AppIdPermission.UPDATE_DAYS_ON_SITE,
    assignment: AppIdPermission.ASSIGNMENT_DAYS_ON_SITE,
    delete: AppIdPermission.DELETE_DAYS_ON_SITE,
  },
  generalsDaysOnSite: {
    view: AppIdPermission.VIEW_GENERALS_DAYS_ON_SITE,
  },
  mandatoryDays: {
    view: AppIdPermission.VIEW_MANDATORY_DAYS,
  },
  nonWorkinsgDays: {
    view: AppIdPermission.VIEW_NON_WORKINGS_DAYS,
    create: AppIdPermission.CREATE_NON_WORKINGS_DAYS,
    delete: AppIdPermission.DELETE_NON_WORKINGS_DAYS,
    viewWorkshiftMenu: AppIdPermission.VIEW_NON_WORKINGS_DAYS_WORKSHIFTS,
  },
  parameters: {
    view: AppIdPermission.VIEW_PARAMETERS,
    update: AppIdPermission.UPDATE_PARAMETERS,
  },
  branchs: {
    view: AppIdPermission.VIEW_BRANCHS,
    edit: AppIdPermission.EDIT_BRANCHS,
    delete: AppIdPermission.DELETE_BRANCHS,
    create: AppIdPermission.CREATE_BRANCHS,
  },
  shifts: {
    view: AppIdPermission.VIEW_SHIFTS,
    edit: AppIdPermission.EDIT_SHIFTS,
    delete: AppIdPermission.DELETE_SHIFTS,
    create: AppIdPermission.CREATE_SHIFTS,
  },
  novelty: {
    view: AppIdPermission.VIEW_NOVELTYS,
    create: AppIdPermission.CREATE_NOVELTYS,
    delete: AppIdPermission.DELETE_NOVELTYS,
    update: AppIdPermission.UPDATE_NOVELTYS,
  },
  typeNovelty: {
    view: AppIdPermission.VIEW_TYPE_NOVELTY,
  },

  configurationDays: {
    view: AppIdPermission.VIEW_CONFIGURATION_DAYS,
    create: AppIdPermission.CREATE_CONFIGURATION_DAYS,
  },
  legalHour: {
    view: AppIdPermission.VIEW_LEGAL_HOURS,
    create: AppIdPermission.CREATE_LEGAL_HOURS,
    update: AppIdPermission.UPDATE_LEGAL_HOURS,
  },
  toleranceView: {
    view: AppIdPermission.VIEW_TOLERANCE_MARKING_SHIFT,
  },
  commercialCalendar: {
    view: AppIdPermission.VIEW_EVENT,
    create: AppIdPermission.CREATE_EVENT,
    edit: AppIdPermission.UPDATE_EVENT,
  },
  eventType: {
    view: AppIdPermission.VIEW_TYPE_EVENT,
  },
  workShift: {
    view: AppIdPermission.VIEW_WORK_SHIFTS,
    create: AppIdPermission.CREATE_WORK_SHIFTS,
    update: AppIdPermission.UPDATE_WORK_SHIFTS,
    assignment: AppIdPermission.ASSIGNMENT_WORK_SHIFTS,
    delete: AppIdPermission.DELETE_WORK_SHIFTS,
  },
  position: {
    view: AppIdPermission.VIEW_POSITIONS,
    create: AppIdPermission.CREATE_POSITIONS,
  },
  typeShiftReport: {
    view: AppIdPermission.VIEW_TYPE_SHIFT,
  },
  request: {
    view: AppIdPermission.VIEW_REQUEST,
  },
  customReport: {
    view: AppIdPermission.VIEW_CUSTOM_REPORT,
  },
  dashboard: {
    view: AppIdPermission.VIEW_DASHBOARD,
  },
  payrollSettlementReport: {
    view: AppIdPermission.VIEW_PAYROLL_SETTLEMENT_REPORT,
  },
  alternationRequest: {
    view: AppIdPermission.VIEW_ALTERNATION_REQUESTS,
  },
  demandLevel: {
    view: AppIdPermission.VIEW_DEMAND_LEVEL,
  },
};
